version: '3'
services:
  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install &&
             npm run build-tailwind &&
             npm run dev"


